package com.paytrace.payment;
public enum PaymentEventType {
  PAYMENT_CREATED, PAYMENT_INITIATED, PAYMENT_AUTHORIZED, PAYMENT_CAPTURED, PAYMENT_FAILED, PAYMENT_CANCELLED, PAYMENT_REVERSED, PAYMENT_REFUNDED, PAYMENT_SETTLED,
  PROVIDER_REQUEST_SENT, PROVIDER_TIMEOUT, PROVIDER_AUTHORIZED, PROVIDER_CAPTURED, PROVIDER_FAILED, PROVIDER_REFUNDED,
  CLIENT_RETRY, IDEMPOTENCY_HIT, IDEMPOTENCY_CONFLICT, WEBHOOK_RECEIVED, WEBHOOK_DUPLICATE, WEBHOOK_OUT_OF_ORDER, WEBHOOK_PROCESSED,
  LEDGER_POSTED, LEDGER_FAILED, LEDGER_RECONCILED, SETTLEMENT_RECEIVED, SETTLEMENT_MISSING
}
