package com.paytrace.payment;
import com.paytrace.common.Hashing; import com.paytrace.ledger.DoubleEntryLedger; import com.paytrace.provider.*; import com.paytrace.timeline.CanonicalStateResolver; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.locks.*;
@Service public class PaymentService {
 private final PaymentRepository payments; private final PaymentEventRepository events; private final PaymentProviderPort provider; private final ProviderPaymentRepository providerPayments; private final DoubleEntryLedger ledger; private final CanonicalStateResolver resolver; private final ConcurrentMap<String,ReentrantLock> locks=new ConcurrentHashMap<>();
 public PaymentService(PaymentRepository p,PaymentEventRepository e,PaymentProviderPort pr,ProviderPaymentRepository pp,DoubleEntryLedger l,CanonicalStateResolver r){payments=p;events=e;provider=pr;providerPayments=pp;ledger=l;resolver=r;}
 public PaymentView create(CreatePaymentRequest request,String idempotencyKey,ProviderFaultMode mode){if(idempotencyKey==null||idempotencyKey.isBlank())throw new MissingIdempotencyKeyException();var lock=locks.computeIfAbsent(idempotencyKey,k->new ReentrantLock());lock.lock();try{return createLocked(request,idempotencyKey,mode);}finally{lock.unlock();}}
 @Transactional protected PaymentView createLocked(CreatePaymentRequest request,String key,ProviderFaultMode mode){String hash=requestHash(request);var existing=payments.findByIdempotencyKey(key);if(existing.isPresent()){if(!existing.get().requestHash().equals(hash))throw new IdempotencyConflictException();reconcileProviderCapture(existing.get());events.save(new PaymentEventEntity(existing.get().id(),PaymentEventType.IDEMPOTENCY_HIT,EventSource.MERCHANT,Instant.now(),key,hash,"{}"));return view(existing.get(),true);}var payment=payments.save(new PaymentEntity(UUID.randomUUID(),request.merchantReference(),key,hash,request.amount(),request.currency()));event(payment,PaymentEventType.PAYMENT_CREATED,EventSource.MERCHANT);event(payment,PaymentEventType.PAYMENT_INITIATED,EventSource.MERCHANT);event(payment,PaymentEventType.PROVIDER_REQUEST_SENT,EventSource.SYSTEM);
  try {var result=provider.createAndCapture(payment.id(),request.amount(),request.currency(),mode);payment.providerPaymentId(result.providerPaymentId());if(result.state()==ProviderState.CAPTURED){event(payment,PaymentEventType.PROVIDER_CAPTURED,EventSource.PROVIDER);ledger.postCapture(payment.id(),request.amount(),request.currency());event(payment,PaymentEventType.LEDGER_POSTED,EventSource.LEDGER);payment.states(PaymentState.CAPTURED,PaymentState.CAPTURED);}else{event(payment,PaymentEventType.PROVIDER_FAILED,EventSource.PROVIDER);payment.states(PaymentState.FAILED,PaymentState.FAILED);}payments.save(payment);return view(payment,false);}catch(MockPaymentProvider.ProviderTimeoutException timeout){event(payment,PaymentEventType.PROVIDER_TIMEOUT,EventSource.MERCHANT);payments.save(payment);throw timeout;}}
 public PaymentView get(UUID id){return view(payments.findById(id).orElseThrow(()->new NoSuchElementException("Payment not found")),false);} public List<PaymentView> list(){return payments.findAll().stream().map(p->view(p,false)).toList();}
 @Transactional public PaymentView reconstruct(UUID id){var p=payments.findById(id).orElseThrow(()->new NoSuchElementException("Payment not found"));var r=resolver.resolve(events.findByPaymentIdOrderByOccurredAtAsc(id));p.states(p.observedState(),r.canonicalState());return view(payments.save(p),false);}
 private void reconcileProviderCapture(PaymentEntity payment){providerPayments.findByPaymentId(payment.id()).filter(p->p.state()==ProviderState.CAPTURED).ifPresent(p->{if(payment.providerPaymentId()==null){payment.providerPaymentId(p.providerPaymentId());event(payment,PaymentEventType.PROVIDER_CAPTURED,EventSource.PROVIDER);ledger.postCapture(payment.id(),payment.amount(),payment.currency());event(payment,PaymentEventType.LEDGER_POSTED,EventSource.LEDGER);payment.states(PaymentState.CAPTURED,PaymentState.CAPTURED);payments.save(payment);}});}
 private void event(PaymentEntity p,PaymentEventType type,EventSource source){events.save(new PaymentEventEntity(p.id(),type,source,Instant.now(),null,null,"{}"));} private String requestHash(CreatePaymentRequest r){return Hashing.sha256(r.merchantReference()+"|"+r.amount().stripTrailingZeros().toPlainString()+"|"+r.currency());} private PaymentView view(PaymentEntity p,boolean replay){return new PaymentView(p.id(),p.merchantReference(),p.idempotencyKey(),p.amount(),p.currency(),p.observedState(),p.canonicalState(),p.providerPaymentId(),p.createdAt(),replay);}
 public static class IdempotencyConflictException extends RuntimeException{public IdempotencyConflictException(){super("Idempotency key was reused with a different payload");}} public static class MissingIdempotencyKeyException extends RuntimeException{public MissingIdempotencyKeyException(){super("Idempotency-Key header is required");}}
}
