package com.paytrace.provider;
public enum ProviderFaultMode { NORMAL, TIMEOUT_BEFORE_PROCESSING, TIMEOUT_AFTER_CAPTURE, DUPLICATE_CAPTURE_RESPONSE, DELAYED_RESPONSE, FAILED_CAPTURE, REFUND_TIMEOUT }
