package com.paytrace.integrity;
import com.paytrace.ledger.*; import com.paytrace.payment.*; import com.paytrace.provider.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@Service public class IntegrityEngine {
 private final PaymentRepository payments; private final PaymentEventRepository events; private final ProviderPaymentRepository providers; private final LedgerTransactionRepository ledgerTransactions; private final LedgerEntryRepository ledgerEntries; private final InvariantResultRepository results;
 public IntegrityEngine(PaymentRepository p,PaymentEventRepository e,ProviderPaymentRepository pr,LedgerTransactionRepository lt,LedgerEntryRepository le,InvariantResultRepository r){payments=p;events=e;providers=pr;ledgerTransactions=lt;ledgerEntries=le;results=r;}
 @Transactional public List<InvariantResult> evaluate(UUID paymentId){var payment=payments.findById(paymentId).orElseThrow();var provider=providers.findByPaymentId(paymentId);var txs=ledgerTransactions.findByPaymentId(paymentId);var output=new ArrayList<InvariantResult>();
  output.add(new InvariantResult("IdempotencyInvariant",true,"Unique idempotency key maps to payment "+paymentId));
  long captureEvents=events.countByPaymentIdAndEventType(paymentId,PaymentEventType.PROVIDER_CAPTURED);output.add(new InvariantResult("CaptureInvariant",captureEvents<=1 && provider.map(p->p.captureCount()<=1).orElse(true),"Provider capture evidence count="+captureEvents));
  boolean balanced=txs.stream().allMatch(tx->{var sum=ledgerEntries.findByTransactionId(tx.id()).stream().map(e->e.direction()==EntryDirection.DEBIT?e.amount():e.amount().negate()).reduce(BigDecimal.ZERO,BigDecimal::add);return sum.compareTo(BigDecimal.ZERO)==0;});output.add(new InvariantResult("LedgerBalanceInvariant",balanced,"Ledger transactions evaluated="+txs.size()));
  boolean amountMatches=provider.map(p->p.state()!=ProviderState.CAPTURED||p.amount().compareTo(payment.amount())==0).orElse(payment.canonicalState()!=PaymentState.CAPTURED);output.add(new InvariantResult("CapturedAmountInvariant",amountMatches,"Provider amount matches canonical payment amount when captured"));
  boolean settlementValid=payment.canonicalState()!=PaymentState.SETTLED||events.findByPaymentIdOrderByOccurredAtAsc(paymentId).stream().anyMatch(e->e.eventType()==PaymentEventType.PROVIDER_CAPTURED||e.eventType()==PaymentEventType.PAYMENT_CAPTURED);output.add(new InvariantResult("SettlementInvariant",settlementValid,"Settled payment has captured ancestor"));
  boolean providerRef=payment.canonicalState()!=PaymentState.CAPTURED||payment.providerPaymentId()!=null;output.add(new InvariantResult("ProviderReferenceInvariant",providerRef,"Captured payment has provider reference"));
  boolean refundSource=events.findByPaymentIdOrderByOccurredAtAsc(paymentId).stream().noneMatch(e->e.eventType()==PaymentEventType.PAYMENT_REFUNDED)||events.findByPaymentIdOrderByOccurredAtAsc(paymentId).stream().anyMatch(e->e.eventType()==PaymentEventType.PROVIDER_CAPTURED);output.add(new InvariantResult("RefundSourceInvariant",refundSource,"Refund evidence is tied to capture evidence"));
  results.saveAll(output.stream().map(r->new InvariantResultEntity(paymentId,r)).toList()); return List.copyOf(output); }
 public List<InvariantResult> results(UUID paymentId){return results.findByPaymentId(paymentId).stream().map(r->new InvariantResult(r.invariantName(),r.passed(),r.evidence())).toList();}
}
